### ISSUE TITLE
Support non-interactive mode

### ISSUE THREAD

**Issue by bentona** [minimaxir/ctrl-gce#3]
This worked like a charm, thanks so much. 

I'm wondering about supporting non-interactive mode e.g. maybe an argument that is the name of a file with inputs? Seems like it would involve re-writing some of `generation.py`. My python is novice-level, but happy to take a stab at this if you'd be interested in collabing on it / it seems within the scope of the project.

**Comment by minimaxir** [comment]
Those changes should be proposed at the source repo; the design goal here isn't like gpt-2-simple. The source `generation.py` appears to be in flux.

**Comment by bentona** [comment]
makes sense, thanks.
