### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by julienmarie** [minimaxir/ctrl-gce#5]
I'm regularly getting this error. Any way to circumvent it ?

Traceback (most recent call last):
  File "generation.py", line 275, in <module>
    print(tokens_generated_so_far)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 289: ordinal not in range(128)

**Comment by minimaxir** [comment]
That's likely a Python 2/3 error. I see you filed upstream which is the better place to fix it.
